### ISSUE TITLE
make the pin 1 marker much more obvious 

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/breakout-pcb#5]

**Comment by urish** [comment]
Is this for TT05? or later

**Comment by mattvenn** [comment]
All boards in use and in future. A tiny dot or similar isn't clear enough

**Comment by urish** [comment]
@psychogenic can you make this change and include it in the gerber files for TT05 carrier boards?

**Comment by psychogenic** [comment]
Gave it le fat arrow, think it'll be plenty clear
![farrow](https://github.com/TinyTapeout/breakout-pcb/assets/1799255/10cf736c-394c-4c74-8ad4-c40b0ba79298)

**Comment by urish** [comment]
Thanks! maybe even write "1" or "Pin 1" on top, to be super duper clear?

**Comment by psychogenic** [comment]
Is it worth it?  Feels like anyone doing PCBA with a QFN can probably handle the hint.  But I'll do it if ya like.

**Comment by psychogenic** [comment]
Ok, this would be hard to miss then
![impossibletomiss](https://github.com/TinyTapeout/breakout-pcb/assets/1799255/453aa9c3-c614-489e-9041-599fd96d91ae)

**Comment by urish** [comment]
Beauty!
