### ISSUE TITLE
make pin1 marker for the black qfn breakout

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/breakout-pcb#6]
Proppy in the discord just soldered it the wrong way round.

**Comment by urish** [comment]
Similar to #5

**Comment by mattvenn** [comment]
yeah. all boards should have a massive pin 1 marker

**Comment by psychogenic** [comment]
Done and will do for future, sent to the Stu
![fatone](https://github.com/TinyTapeout/breakout-pcb/assets/1799255/c8b94a81-8902-4119-b774-33d22453eb7b)
